services:
  - title: "Oikyo Workbench"
    description: "A self-hosted, IDE-like application that unifies the fine-tuning workflow, providing maximum security and control for enterprises."
    icon: "strategy-icon.svg"
    features:
      - "Model Discovery and management across 200+ small and large models"
      - "Train Models with your organization's data within your data boundary"
      - "Evals, Inference, closing the loop from a unified IDE"

  - title: "Oikyo Cloud"
    description: "A fully managed SaaS platform providing the infrastructure for training, evaluation, and inference, eliminating operational overhead."
    icon: "platform-icon.svg"
    features:
      - "Cloud-based model fine-tuning and hosting"
      - "Performance optimization and online monitoring of training and eval jobs"
      - "Flexibility with Pay-as-you-go and Enterprise pricing"

  - title: "Oikyo Insights"
    description: "Enabling continuous evaluation of deployed models for better accuracy and domain relevance."
    icon: "training-icon.svg"
    features:
      - "Continuous Model Evaluation"
      - "Feedback loops"
      - "Model Governance"
      - "Insights Dashboard"
